# .github/workflows/vercel-ci.yml
name: Vercel CI/CD

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Setup PNPM
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      # Install dependencies
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      # Run lint + validation
      - name: Validate code
        run: pnpm validate

      # Build project
      - name: Build project
        run: pnpm build

      # Deploy to Vercel
      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }} # Required
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }} # Required
          working-directory: .
          prod: true
